### ISSUE TITLE
Authentication failure in GitHub Page publish stage

### ISSUE THREAD

**Issue by boxsnake** [qiwi/semantic-release-gh-pages-plugin#181]
```json5
# package.json
"release": {
  "branches": [
    "main"
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@qiwi/semantic-release-gh-pages-plugin",
      {
        "msg": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        "src": "docs",
        "dst": ".",
        "branch": "docs",
        "pullTagsBranch": "",
        "dotfiles": true
      }
    ],  
    [
      "@semantic-release/github",
      {
        "assets": [
          {
            "path": "docs/**/*",
            "label": "docs bundle"
          }
        ]
      }
    ]
  ]
}
```

GitHub Actions error log: (unrelated parts are omitted)
```bash
[8:46:09 AM] [semantic-release] [@qiwi/semantic-release-gh-pages-plugin] › ✖  Publish docs failure ProcessError: remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/boxsnake/js-tutorial.git/'

    at ChildProcess.<anonymous> (/home/runner/work/js-tutorial/js-tutorial/node_modules/gh-pages/lib/git.js:42:16)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  code: 128
}
[8:46:09 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@qiwi/semantic-release-gh-pages-plugin"
[8:46:09 AM] [semantic-release] › ✖  An error occurred while running semantic-release: ProcessError: remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/boxsnake/js-tutorial.git/'

    at ChildProcess.<anonymous> (/home/runner/work/js-tutorial/js-tutorial/node_modules/gh-pages/lib/git.js:42:16)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  code: 128,
  pluginName: '@qiwi/semantic-release-gh-pages-plugin'
}
ProcessError: remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/boxsnake/js-tutorial.git/'

    at ChildProcess.<anonymous> (/home/runner/work/js-tutorial/js-tutorial/node_modules/gh-pages/lib/git.js:42:16)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  code: 128,
  pluginName: '@qiwi/semantic-release-gh-pages-plugin'
}error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by antongolub** [comment]
@boxsnake,

Seems like you need to issue a new token. We still use this plugin [as a part of out release toolkit](https://github.com/qiwi/semantic-release-toolkit/blob/master/packages/config/src/main/js/index.js) and everything works as expected: [release config](https://github.com/antongolub/tsc-esm-fix/blob/master/.github/workflows/ci.yaml#L159), [release log](https://github.com/antongolub/tsc-esm-fix/runs/5851258635?check_suite_focus=true#step:7:82), [gh-pages branch](https://github.com/antongolub/tsc-esm-fix/tree/gh-pages)

**Comment by antongolub** [comment]
@boxsnake,

There's an alternative: https://github.com/qiwi/semantic-release-toolkit/pull/127
```json
[
      '@qiwi/semrel-metabranch',
      {
        publish: {
          action: 'push',
          branch: 'gh-pages',
          from: './docs',
          to: './',
          message: 'update docs ${nextRelease.gitTag}',
        }
      }
    ],
```

**Comment by antongolub** [comment]
It seems, that everything is fine now.
